#!/usr/bin/env bash

trigger-letsencrypt-cron-entries() {
  if [[ -f "${DOKKU_LIB_ROOT}/data/letsencrypt/autorenew" ]]; then
    echo "@daily;dokku letsencrypt:auto-renew;/var/log/dokku/letsencrypt.log"
  fi
}

trigger-letsencrypt-cron-entries "$@"
