#!/usr/bin/env bash
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

migrate_config_to_props() {
  local old_global_grace_period=$(config_get --global DOKKU_LETSENCRYPT_GRACEPERIOD)
  local old_global_extra_args=$(config_get --global DOKKU_LETSENCRYPT_ARGS)
  [[ -n "$old_global_grace_period" ]] && fn-plugin-property-write "letsencrypt" "--global" "graceperiod" "$old_global_grace_period"
  [[ -n "$old_global_extra_args" ]] && fn-plugin-property-write "letsencrypt" "--global" "lego-args" "$old_global_extra_args"

  for app in $(dokku_apps); do
    if [[ "$app" == "=====>" ]] || [[ "$app" == "My" ]] || [[ "$app" == "Apps" ]]; then continue; fi
    if [[ "$(letsencrypt_is_active "$app")" ]]; then
      local old_grace_period=$(config_get "$app" DOKKU_LETSENCRYPT_GRACEPERIOD || echo $((60 * 60 * 24 * 30)))
      local old_extra_args="$(config_get "$app" DOKKU_LETSENCRYPT_ARGS || echo '')"

      [[ -n "$old_grace_period" ]] && fn-plugin-property-write "letsencrypt" "$app" "graceperiod" "$old_grace_period"
      [[ -n "$old_extra_args" ]] && fn-plugin-property-write "letsencrypt" "$app" "lego-args" "$old_extra_args"
    fi
  done
}

plugin-install() {
  pull-docker-image() {
    declare IMAGE="$1"
    if [[ "$PLUGIN_DISABLE_PULL" == "true" ]]; then
      echo " !     ${PLUGIN_DISABLE_PULL_VARIABLE} environment variable detected. Not running pull command." 1>&2
      echo " !        docker pull ${IMAGE}" 1>&2
      return
    fi
    if [[ "$(docker images -q "${IMAGE}" 2>/dev/null)" == "" ]]; then
      docker pull "${IMAGE}"
    fi
  }

  pull-docker-image "${PLUGIN_IMAGE}:${PLUGIN_IMAGE_VERSION}"
  fn-plugin-property-setup "letsencrypt"
  local cron_cmd=$(fn-plugin-property-get "letsencrypt" "--global" "cron-cmd")
  local has_migration_happened=$(fn-plugin-property-get "letsencrypt" "--global" "has_config_migration_happened")
  [[ -z "$cron_cmd" ]] && fn-plugin-property-write "letsencrypt" "--global" "cron-cmd" "$PLUGIN_AVAILABLE_PATH/letsencrypt/cron-job"
  [[ -z "$has_migration_happened" ]] && migrate_config_to_props && fn-plugin-property-write "letsencrypt" "--global" "has_config_migration_happened" "1"

  mkdir -p "${DOKKU_LIB_ROOT}/data/letsencrypt"
  chown -R "${DOKKU_SYSTEM_USER}:${DOKKU_SYSTEM_GROUP}" "${DOKKU_LIB_ROOT}/data/letsencrypt"
}

plugin-install "$@"
