#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

trigger-letsencrypt-post-domains-update() {
  declare desc="updates cert file when domains are added or set"
  declare trigger="post-domains-update"
  declare APP="$1" ACTION="$2"

  if [[ "$ACTION" == "add" ]] || [[ "$ACTION" == "set" ]]; then
    dokku_log_warn "Please run dokku letsencrypt:enable to add https support to the new domain"
  fi
}

trigger-letsencrypt-post-domains-update "$@"
