#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/functions"


letsencrypt_domains_cmd() {
  #shellcheck disable=SC2034
  declare desc="set domains for a client within an app"

  local app="$2"; verify_app_name "$app"
  local client="$3"
  local domains="$4"

  local app_root="$DOKKU_ROOT/$app"
  local le_root="$app_root/letsencrypt"
  local client_root="$le_root/$client"

  letsencrypt_create_root "$app"

  mkdir -p $client_root

  dokku_log_info1 "Adding domains to $client_root/DOMAINS..."

  echo "$domains" > "$client_root/DOMAINS"
}

letsencrypt_domains_cmd "$@"
