#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/nginx-vhosts/functions"
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/functions"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

letsencrypt_acmeproxy_on() {
  #shellcheck disable=SC2034
  declare desc="enable ACME proxy for an app"
  local app="$1"
  local acme_port="$2"

  local app_root="$DOKKU_ROOT/$app"
  local app_config_dir="$app_root/nginx.conf.d"

  dokku_log_info1 "Enabling ACME proxy for ${app}..."

  # ensure the nginx.conf.d directory exists
  [[ -d "$app_config_dir" ]] || mkdir "$app_config_dir"

  # insert acme_port into config template, place resulting config in nginx.conf.d
  sigil -f "$PLUGIN_AVAILABLE_PATH/letsencrypt/templates/letsencrypt.conf.sigil" \
    ACME_PORT="$acme_port" \
    >"$app_config_dir/letsencrypt.conf"

  restart_nginx
}

letsencrypt_acmeproxy_off() {
  #shellcheck disable=SC2034
  declare desc="disable ACME proxy for an app"
  local app="$1"

  local app_root="$DOKKU_ROOT/$app"
  local app_config_dir="$app_root/nginx.conf.d"

  dokku_log_info1 "Disabling ACME proxy for $app..."

  [[ -f "$app_config_dir/letsencrypt.conf" ]] && rm "$app_config_dir/letsencrypt.conf"

  restart_nginx
}

letsencrypt_link() {
  #shellcheck disable=SC2034
  declare desc="symlink let's encrypt certificates so they can be found by dokku"

  local app="$1"
  local config_dir="$2"

  local app_root="$DOKKU_ROOT/$app"
  local le_root="$app_root/letsencrypt"

  dokku_log_info1 "Installing let's encrypt certificates"

  # link the current config directory to 'current'
  ln -nsf "$config_dir" "$le_root/certs/current"

  # install the let's encrypt certificate for the app
  if [[ -z $DOKKU_APP_NAME ]]; then
    dokku certs:add "$app" "$le_root/certs/current/fullchain.pem" "$le_root/certs/current/key.pem"
  else
    dokku certs:add "$le_root/certs/current/fullchain.pem" "$le_root/certs/current/key.pem"
  fi
}

letsencrypt_acme() {
  #shellcheck disable=SC2034
  declare desc="perform actual ACME validation procedure"
  local app="$1"
  local acme_port="$2"

  letsencrypt_create_root "$app"

  dokku_log_info1 "Getting letsencrypt certificate for ${app}..."

  # read simp_le arguments from appropriate config file into the config array
  local config_dir="$(letsencrypt_configure_and_get_dir "$app")"
  read -r -a config <"$config_dir/config"

  eval "$(config_export global)"
  eval "$(config_export app "$app")"

  local graceperiod="${DOKKU_LETSENCRYPT_GRACEPERIOD:-$((60 * 60 * 24 * 30))}"

  # run letsencrypt as a docker container using "certonly" mode
  # port 80 of the standalone webserver will be forwarded by the proxy
  set +e
  docker run --rm \
    -p "$acme_port:80" \
    -v "$config_dir:/certs" \
    "${PLUGIN_IMAGE}:${PLUGIN_IMAGE_VERSION}" \
    -f account_key.json \
    -f account_reg.json \
    -f fullchain.pem -f chain.pem -f cert.pem -f key.pem \
    --valid_min "${graceperiod}" \
    "${config[@]}"

  local simple_result=$?
  set -e

  # handle simp_le return codes
  # see https://github.com/kuba/simp_le/blob/master/README.rst#manifest
  if [[ $simple_result == 0 ]]; then
    # got certificate
    dokku_log_info1 "Certificate retrieved successfully."

  elif [[ $simple_result == 1 ]]; then
    # no renewal necessary
    dokku_log_info1 "No renewal necessary"

  else
    # error - don't try to link certificates
    dokku_log_info1 "Certificate retrieval failed!"
    return

  fi

  letsencrypt_link "$app" "$config_dir"
  nginx_build_config "$app"
}

fn-lentsencrypt-enable() {
  declare APP="$1"

  verify_app_name "$APP"
  dokku_log_info2 "Let's Encrypt $APP"

  # dynamically choose a port for the letsencrypt standalone authenticator
  local acme_port=$(get_available_port)

  letsencrypt_check_email "$APP"

  letsencrypt_update

  letsencrypt_acmeproxy_on "$APP" "$acme_port"
  letsencrypt_acme "$APP" "$acme_port" || true # remove ACME proxy even if this fails
  letsencrypt_acmeproxy_off "$APP"

  dokku_log_verbose "done"
}

cmd-letsencrypt-enable() {
  #shellcheck disable=SC2034
  declare desc="Enable or renew letsencrypt for an app"
  declare cmd="letsencrypt:enable"
  [[ "$1" == "$cmd" ]] && shift 1

  # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"
  local argv=("$@")
  [[ ${argv[0]} == "$cmd" ]] && shift 1
  [[ ! -z $DOKKU_APP_NAME ]] && set -- $DOKKU_APP_NAME $@
  set -- $cmd $@
  ##

  declare APP="$1"
  if [[ "$APP" == "--all" ]]; then
    for app in $(dokku_apps); do
      fn-lentsencrypt-enable "$app"
    done
  else
    fn-lentsencrypt-enable "$APP"
  fi
}

cmd-letsencrypt-enable "$@"
