#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/functions"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-letsencrypt-list() {
  #shellcheck disable=SC2034
  declare desc="list letsencrypt-secured apps and certificate expiries"
  declare cmd="letsencrypt:list"
  [[ "$1" == "$cmd" ]] && shift 1

  dokku_col_log_info1_quiet "App name" "Certificate Expiry" "Time before expiry" "Time before renewal"

  letsencrypt_list_apps_and_expiry \
    | sort -nk2 \
    | while IFS=$'\t' read -r -a appExpiry; do
      expire_date=$(date -d "@${appExpiry[1]}" +"%F %T")
      expire_time=$(letsencrypt_format_timediff "${appExpiry[3]}")
      renew_time=$(letsencrypt_format_timediff "${appExpiry[4]}")
      dokku_col_log_msg "${appExpiry[0]}" "${expire_date}" "${expire_time}" "${renew_time}"
    done
}

cmd-letsencrypt-list "$@"
