#!/usr/bin/env bash
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/nginx-vhosts/functions"
source "$PLUGIN_AVAILABLE_PATH/letsencrypt/internal-functions"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

letsencrypt_acme_revoke() {
  #shellcheck disable=SC2034
  declare desc="perform actual certificate revocation"
  local app="$1"

  fn-letsencrypt-create-root "$app"

  dokku_log_info1 "Revoking letsencrypt certificate for ${app}..."
  local acme_port=$(get_available_port)

  # read arguments from appropriate config file into the config array
  config_dirs="$(fn-letsencrypt-configure-and-get-dir "$app")"
  host_config_dir="$(echo "$config_dirs" | cut -d: -f1)"
  container_config_dir="$(echo "$config_dirs" | cut -d: -f2)"
  read -r -a config <"$container_config_dir/config"

  # run letsencrypt as a docker container using "certonly" mode
  # port 80 of the standalone webserver will be forwarded by the proxy
  set +e
  export DOKKU_UID=$(id -u)
  export DOKKU_GID=$(id -g)
  mkdir -p "$DOKKU_LIB_ROOT/data/letsencrypt/$APP"
  docker run --rm \
    --user $DOKKU_UID:$DOKKU_GID \
    -p "$acme_port:$acme_port" \
    -v "$host_config_dir:/certs" \
    -v "$DOKKU_LIB_ROOT/data/letsencrypt/$APP:/webroot" \
    "${PLUGIN_IMAGE}:${PLUGIN_IMAGE_VERSION}" \
    "${config[@]}" revoke | sed "s/^/       /"

  local exit_code=$?
  set -e

  # handle return codes
  if [[ $exit_code == 0 ]]; then
    # certificate revoked
    dokku_log_info1 "Certificate revoked successfully."
  else
    # error - don't try to link certificates
    dokku_log_info1 "Certificate revocation failed (code $simple_result)!"
    return
  fi

  local domain="$(get_app_domains "$app" | xargs | awk '{print $1}')"

  # move revoked certificates away
  mv -f "$container_config_dir/certificates/$domain.crt" "$container_config_dir/certificates/$domain.crt.revoked"
  mv -f "$container_config_dir/certificates/$domain.issuer.crt" "$container_config_dir/certificates/$domain.issuer.crt"
  mv -f "$container_config_dir/certificates/$domain.key" "$container_config_dir/certificates/$domain.key"
  mv -f "$container_config_dir/certificates/$domain.key" "$container_config_dir/certificates/$domain.key"
  mv -f "$container_config_dir/certificates/$domain.pem" "$container_config_dir/certificates/key.pem.revoked"

  # removing the certificate will automatically reconfigure nginx
  if [[ -z $DOKKU_APP_NAME ]]; then
    dokku certs:remove "$app"
  else
    dokku certs:remove
  fi

}

cmd-letsencrypt-revoke() {
  #shellcheck disable=SC2034
  declare desc="Revoke a certificate"
  declare cmd="letsencrypt:revoke"
  [[ "$1" == "$cmd" ]] && shift 1

  # Support --app/$DOKKU_APP_NAME flag by reordering args into "$cmd $DOKKU_APP_NAME $@"
  local argv=("$@")
  [[ -n "$DOKKU_APP_NAME" ]] && set -- $DOKKU_APP_NAME $@
  ##

  declare APP="$1"
  verify_app_name "$APP"

  dokku_log_info2 "Revoke letsencrypt certificate from ${APP}..."

  fn-letsencrypt-check-email "$APP"
  letsencrypt_acme_revoke "$APP" || true

  dokku_log_verbose "done"
}

cmd-letsencrypt-revoke "$@"
